print(" The Loop from 1 to 10 ")
for i in range(10):
    print("The value of i is currently", i)

print("""
Well Done, now the second one is... 2 to 8 """
)

for i in range(2, 8):
    print("The value of i is currently", i)

print("""
Now the third one is the following
for i in range(2, 8, 3):
    2 (starting number) → 5 (2 increment by 3 equals 5 -
    the number is within the range from 2 to 8) → 8 (5 increment by 3 equals 8 -
    the number is not within the range from 2 to 8,
    because the stop parameter is not included in the sequence of numbers generated by the function.) """)

for i in range(2, 8, 3):
    print("The value of i is currently", i)

print("""
pow = 1
for exp in range(16):
    print("2 to the power of", exp, "is", pow)
    pow *= 2""")

pow = 1
for exp in range(16):
    print("2 to the power of", exp, "is", pow)
    pow *= 2
